### ISSUE TITLE
Create a module similar to autograder_utils, but for pytest instead of unittest

### ISSUE THREAD

**Issue by pconrad** [ucsb-gradescope-tools/ucsb-gradescope-tools.github.io#4]
Create a module similar to Gradescope's provided one for `unittest` (below), but for `pytest`

https://github.com/gradescope/gradescope-utils/tree/master/gradescope_utils/autograder_utils

That is, the autograder_utils module above works for `unittest`.  

Can we make it work for `pytest` instead?  Note that `pytest` is the preferred unit testing framework of several UCSB CS8 instructors, including Profs. Mirza, R.K. Wang, and Conrad.    

At the moment, the work around is that we have to write unit tests in the pytest framework for the student facing example code, then rewrite all of them in the `unitttest` framework by hand so that we can do autograding with Gradescope using the same unit tests.

This is straightforward, but time-consuming and error prone, and adds little value.

**Comment by caitscarberry** [comment]
Done in https://github.com/ucsb-gradescope-tools/pytest_utils
